### ISSUE TITLE
Error due to environment GITHUB_TOKEN variable not set?

### ISSUE THREAD

**Issue by Bad3r** [clj-holmes/clj-watson-action#8]
Hello,
I am experimenting with adding this action. The action fails due to the environment GITHUB_TOKEN variable being not set. 

The variable is set in the repo, but I am not sure why clj-watson needs to use it or where does it need to be added. 

```edn
** ERROR: **
Exception: #error {
 :cause environment GITHUB_TOKEN variable not set.
 :via
 [{:type java.util.concurrent.ExecutionException
   :message java.lang.Exception: environment GITHUB_TOKEN variable not set.
   :at [java.util.concurrent.FutureTask report FutureTask.java 122]}
  {:type java.lang.Exception
   :message environment GITHUB_TOKEN variable not set.
   :at [clj_watson.diplomat.github.advisory$vulnerabilities_by_package_STAR_ invokeStatic advisory.clj 24]}]
 :trace
 [[clj_watson.diplomat.github.advisory$vulnerabilities_by_package_STAR_ invokeStatic advisory.clj 24]
  [clj_watson.diplomat.github.advisory$vulnerabilities_by_package_STAR_ invoke advisory.clj 17]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$memoize$fn__6946 doInvoke core.clj 6388]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clj_watson.controller.github.vulnerability$scan_dependency invokeStatic vulnerability.clj 18]
  [clj_watson.controller.github.vulnerability$scan_dependency invoke vulnerability.clj 16]
  [clj_watson.controller.github.vulnerability$scan_dependencies$fn__17069 invoke vulnerability.clj 28]
  [clojure.core$pmap$fn__8552$fn__8553 invoke core.clj 7089]
  [clojure.core$binding_conveyor_fn$fn__5823 invoke core.clj 2047]
  [clojure.lang.AFn call AFn.java 18]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [java.lang.Thread run Thread.java 829]]}
```

workflow:
```yml
# https://github.com/clj-holmes/clj-holmes
name: clj-holmes

on:
  push:
    branches: [ "master", 2approvesbeforemerged ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '15 16 * * 6'

permissions:
  contents: read

jobs:
  clj-holmes:
    name: Run clj-holmes scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0

      - name: Scan code
        uses: clj-holmes/clj-holmes-action@200d2d03900917d7eb3c24fc691ab83579a87fcb
        with:
          # rules-repository: 'git://org/private-rules-repo#main'
          output-type: 'sarif'
          output-file: 'clj-holmes-results.sarif'
          fail-on-result: 'false'

      - name: Upload analysis results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd  # v2.2.1
        with:
          sarif_file: ${{github.workspace}}/clj-holmes-results.sarif
          wait-for-processing: true
```
